AWSTemplateFormatVersion: '2010-09-09'
Resources:
 FacialAnalysisTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: FacialAnalysisTable
      AttributeDefinitions:
        - AttributeName: ImageName
          AttributeType: S
        - AttributeName: Confidence
          AttributeType: N
        - AttributeName: Emotion
          AttributeType: S
      KeySchema:
        - AttributeName: ImageName
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: EmotionConfidenceIndex
          KeySchema:
            - AttributeName: Emotion
              KeyType: HASH
            - AttributeName: Confidence
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
