Resources:
 FaceAnalysisesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FaceAnalysises
      AttributeDefinitions:
        - AttributeName: ImageName
          AttributeType: S
        - AttributeName: CalmConfidenceScore
          AttributeType: S
        - AttributeName: HappyConfidenceScore
          AttributeType: S
        - AttributeName: AngryConfidenceScore
          AttributeType: S
        - AttributeName: FrustratedConfidenceScore
          AttributeType: S
      KeySchema:
        - AttributeName: ImageName
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGES