AWSTemplateFormatVersion: '2010-09-09'
Resources:
 FaceAnalysisQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: FaceAnalysisQueue
      FifoQueue: false
      ContentBasedDeduplication: true
Outputs:
 QueueName:
    Description: The name of the queue
    Value: !Ref FaceAnalysisQueue
 QueueURL:
    Description: The URL of the queue
    Value: !GetAtt FaceAnalysisQueue.Arn
 QueueARN:
    Description: The ARN of the queue
    Value: !GetAtt FaceAnalysisQueue.Arn
