AWSTemplateFormatVersion: '2010-09-09'
Resources:
  FaceAnalysisQueue:
    Properties:
      QueueName: FaceAnalysisQueue
      FifoQueue: false
      ContentBasedDeduplication: true
    Type: AWS::SQS::Queue
Outputs:
  QueueName:
    Description: The name of the queue
    Value: FaceAnalysisQueue.QueueName
  QueueURL:
    Description: The URL of the queue
    Value: FaceAnalysisQueue
  QueueARN:
    Description: The ARN of the queue
    Value: FaceAnalysisQueue.Arn